### ISSUE TITLE
Let this script run on Rundeck

### ISSUE THREAD

**Issue by MaEbert1105** [Proemion/Babtec_QM#2]
Hi @Svedrin,
I need your help again to run a script on Rundeck 😃 

Could you help me with this issue?

**Comment by unicolet** [comment]
@Svedrin you could try to replicate the work done in https://github.com/Proemion/Salesforce_Intranet_Synch/issues/23 :)

**Comment by Svedrin** [comment]
@unicolet I'm not sure if it'll work that way: afaict, the python executor step wants to clone a github repo using a deployment key:

![Screenshot_20201116_115136](https://user-images.githubusercontent.com/946488/99244268-245c3380-2802-11eb-98b8-9df322fa25ec.png)

Unfortunately GitHub [does not allow using the same deployment SSH key for multiple repos](https://github.com/Proemion/puppet/issues/866#issuecomment-599569781), and I don't see an option there to specify a deployment key to use. It seems to me like this rules out using the same plugin multiple times. Is my understanding correct?

**Comment by unicolet** [comment]
@Svedrin AFAIU a deployment key is just an ssh key you upload on GH, so it should be possible to use it on more than one repo. The issue you linked refers to forks, maybe that's the difference?

**Comment by unicolet** [comment]
the deploy key (pub and priv) are on the VM where the salesforce sync script runs. I should've added them to vault , in hindsight :-(

**Comment by unicolet** [comment]
@MaEbert1105 btw, does it make sense to create a repo to host a single script? You could have added this script to the other repo or create one where they can all coexist together IMHO

**Comment by unicolet** [comment]
or is this the query you asked me to send via email from metabase? In which care this issue (and perhaps repo) can be closed :-)

**Comment by MaEbert1105** [comment]
@unicolet If we add this script to the other repo, can we define different "run" settings?
So that one script runs once a day and the other once a month?

Yes, this is the request I asked you for, but I need to change the data I got back.
So I need this Python script.

**Comment by unicolet** [comment]
> if we add this script to the other repo, can we define different "run" settings?
So that one script runs once a day and the other once a month?

@MaEbert1105 surely

**Comment by MaEbert1105** [comment]
@unicolet then we can add the scripts to a repo.
Which one should we use?

**Comment by unicolet** [comment]
@MaEbert1105 I'd say to add move it to https://github.com/Proemion/Salesforce_Intranet_Synch ?

**Comment by MaEbert1105** [comment]
@unicolet added with PR [NewStructure](https://github.com/Proemion/Salesforce_Intranet_Synch/pull/28/files#)

**Comment by Svedrin** [comment]
@MaEbert1105 we merged the PR, and I think you created the rundeck job, right? Are we done?

**Comment by MaEbert1105** [comment]
@Svedrin and @unicolet, yes we are done.
Thanks for your help.
